name: demo_app
description: "VisionGRO - AI Paddy Disease Detection & Farm Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  shared_preferences: ^2.3.3
  google_generative_ai: ^0.4.0
  http: ^1.2.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
    - assets/images/paddy_healthy.png
    - assets/images/paddy_diseased.png
    - assets/images/paddy_diseased2.png
    - assets/images/problem1.png
    - assets/images/problem2.jpeg
    - assets/images/problem3.jpeg
    - assets/images/paddyphase/Seed.png
    - assets/images/paddyphase/Baby Plant.png
    - assets/images/paddyphase/Growing.png
    - assets/images/paddyphase/Mature.png
    - assets/images/paddyphase/Harvest.png
