/// Malaysian states and districts for farm location selection
class MalaysianLocations {
  static const Map<String, List<String>> statesAndDistricts = {
    'Johor': [
      'Batu Pahat',
      'Johor Bahru',
      'Kluang',
      'Kota Tinggi',
      'Kulai',
      'Mersing',
      'Muar',
      'Pontian',
      'Segamat',
      'Tangkak',
    ],
    'Kedah': [
      'Baling',
      'Bandar Baharu',
      'Kota Setar',
      'Kuala Muda',
      'Kubang Pasu',
      'Kulim',
      'Langkawi',
      'Padang Terap',
      'Pendang',
      'Pokok Sena',
      'Sik',
      'Yan',
    ],
    'Kelantan': [
      'Bachok',
      'Gua Musang',
      'Jeli',
      'Kota Bharu',
      'Kuala Krai',
      'Machang',
      'Pasir Mas',
      'Pasir Puteh',
      'Tanah Merah',
      'Tumpat',
    ],
    'Melaka': [
      'Alor Gajah',
      'Jasin',
      'Melaka Tengah',
    ],
    'Negeri Sembilan': [
      'Jelebu',
      'Jempol',
      'Kuala Pilah',
      'Port Dickson',
      'Rembau',
      'Seremban',
      'Tampin',
    ],
    'Pahang': [
      'Bentong',
      'Bera',
      'Cameron Highlands',
      'Jerantut',
      'Kuantan',
      'Lipis',
      'Maran',
      'Pekan',
      'Raub',
      'Rompin',
      'Temerloh',
    ],
    'Penang': [
      'Barat Daya',
      'Seberang Perai Selatan',
      'Seberang Perai Tengah',
      'Seberang Perai Utara',
      'Timur Laut',
    ],
    'Perak': [
      'Batang Padang',
      'Hilir Perak',
      'Hulu Perak',
      'Kampar',
      'Kerian',
      'Kinta',
      'Kuala Kangsar',
      'Larut & Matang',
      'Manjung',
      'Muallim',
      'Perak Tengah',
    ],
    'Perlis': [
      'Arau',
      'Kangar',
      'Padang Besar',
    ],
    'Sabah': [
      'Beaufort',
      'Keningau',
      'Kota Belud',
      'Kota Kinabalu',
      'Kudat',
      'Lahad Datu',
      'Papar',
      'Penampang',
      'Ranau',
      'Sandakan',
      'Semporna',
      'Tawau',
      'Tenom',
      'Tuaran',
    ],
    'Sarawak': [
      'Betong',
      'Bintulu',
      'Kapit',
      'Kuching',
      'Limbang',
      'Miri',
      'Mukah',
      'Samarahan',
      'Sarikei',
      'Sibu',
      'Sri Aman',
    ],
    'Selangor': [
      'Gombak',
      'Hulu Langat',
      'Hulu Selangor',
      'Klang',
      'Kuala Langat',
      'Kuala Selangor',
      'Petaling',
      'Sabak Bernam',
      'Sepang',
    ],
    'Terengganu': [
      'Besut',
      'Dungun',
      'Hulu Terengganu',
      'Kemaman',
      'Kuala Nerus',
      'Kuala Terengganu',
      'Marang',
      'Setiu',
    ],
    'W.P. Kuala Lumpur': ['Kuala Lumpur'],
    'W.P. Labuan': ['Labuan'],
    'W.P. Putrajaya': ['Putrajaya'],
  };

  static List<String> get states => statesAndDistricts.keys.toList()..sort();

  static List<String> getDistricts(String state) {
    return statesAndDistricts[state] ?? [];
  }

  // Popular paddy farming areas in Malaysia
  static const List<Map<String, String>> popularPaddyAreas = [
    {'state': 'Kedah', 'district': 'Kota Setar', 'area': 'Alor Setar'},
    {'state': 'Kedah', 'district': 'Kuala Muda', 'area': 'Yan'},
    {'state': 'Perlis', 'district': 'Kangar', 'area': 'Kangar'},
    {'state': 'Selangor', 'district': 'Kuala Selangor', 'area': 'Sekinchan'},
    {'state': 'Perak', 'district': 'Kerian', 'area': 'Bagan Datuk'},
    {'state': 'Kelantan', 'district': 'Kota Bharu', 'area': 'Kota Bharu'},
    {'state': 'Terengganu', 'district': 'Besut', 'area': 'Kampung Raja'},
  ];
}
